FROM flink:1.16.0-scala_2.12

COPY sql-client.sh /opt/sql-client/

RUN mkdir -p /opt/sql-client/

RUN wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-connector-kafka/1.19.0/flink-sql-connector-kafka-1.19.0.jar; \
    wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-connector-jbdc/3.1.1-1.17/flink-connector-jdbc-3.1.1-1.17.jar; \
    wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-json/1.17.1/flink-json-1.17-1.jar; \
    wget -P /opt/sql-client/lib/ https://jdbc.postgresql.org/download/postgresql-42.5.4.jar; \
    wget -P /opt/sql-client/lib/ https://repo.maven.apache.org/maven2/org/apache/flink/flink-sql-avro-confluent-registry/1.19.0/flink-sql-avro-confluent-registry-1.19.0.jar;


WORKDIR /opt/sql-client
ENV SQL_CLIENT_NAME /opt/sql-client

COPY docker-entrypoint.sh /opt/sql-client
RUN chmod +x /opt/sql-client/docker-entrypoint.sh
ENTRYPOINT ["/opt/sql-client/docker-entrypoint.sh"]